import { LegalLayout } from '../../../components/LegalLayout'

export const metadata = {
  title: 'Privacy Policy - Fiabe Magiche',
  description: 'Privacy notice for the Fiabe Magiche app with details on data collection, usage, and GDPR rights.',
}

export default function Page() {
  return (
    <LegalLayout>
      <header className="space-y-2 border-b border-slate-200 pb-6">
        <h1 className="text-3xl font-semibold tracking-tight">PRIVACY POLICY</h1>
        <p>
          <strong>Fiabe Magiche</strong>
          <br />
          <em>Last updated: 14 August 2025</em>
        </p>
      </header>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">1. WHO WE ARE</h2>
        <p>Fiabe Magiche is a mobile application that helps children create personalised stories using artificial intelligence.</p>
        <div className="rounded-xl border border-slate-200 bg-slate-50 px-5 py-4">
          <p>
            <strong>Developer:</strong> Marino Panariello
            <br />
            <strong>Contact:</strong> <a className="text-blue-600 underline-offset-4 hover:underline" href="mailto:marinopanariello@gmail.com">marinopanariello@gmail.com</a>
          </p>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">2. DATA WE COLLECT</h2>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">2.1 Data provided voluntarily</h3>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              <strong>Child&apos;s name</strong> (optional): used only to personalise stories
            </li>
            <li>
              <strong>Child&apos;s age</strong>: ensures age-appropriate content
            </li>
            <li>
              <strong>Creative preferences</strong>: preferred settings and protagonists for stories
            </li>
          </ul>
        </div>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">2.2 Data generated by the app</h3>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              <strong>Stories created</strong>: text, images, and audio produced by the app
            </li>
            <li>
              <strong>Usage preferences</strong>: favourite stories and reading frequency
            </li>
            <li>
              <strong>Minimal technical data</strong>: app version and device type (for support only)
            </li>
          </ul>
        </div>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">2.3 Subscription data</h3>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              <strong>Payment information</strong>: processed exclusively by Apple/Google via RevenueCat
            </li>
            <li>
              <strong>Subscription status</strong>: active/inactive to enable premium features
            </li>
          </ul>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">3. HOW WE USE DATA</h2>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">3.1 Primary purposes</h3>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              <strong>Personalisation</strong>: create stories tailored to each child
            </li>
            <li>
              <strong>App functionality</strong>: save and organise created stories
            </li>
            <li>
              <strong>Age-appropriate content</strong>: filter content based on age
            </li>
            <li>
              <strong>Subscription management</strong>: enable premium features
            </li>
          </ul>
        </div>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">3.2 Legal basis (GDPR)</h3>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              <strong>Consent</strong>: for optional data such as the child&apos;s name
            </li>
            <li>
              <strong>Legitimate interest</strong>: for essential app functionality
            </li>
            <li>
              <strong>Performance of a contract</strong>: for subscription management
            </li>
          </ul>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">4. DATA SHARING</h2>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">4.1 Artificial intelligence services</h3>
          <p>We rely on the following providers to generate stories:</p>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              <strong>Google Gemini</strong>: produces the story text
            </li>
            <li>
              <strong>Runware API</strong>: generates personalised images
            </li>
            <li>
              <strong>Amazon Polly</strong>: produces narration audio
            </li>
          </ul>
          <div className="rounded-xl border-l-4 border-sky-500 bg-sky-50 px-5 py-4">
            <strong>IMPORTANT:</strong> These services receive only the parameters required (age, setting, protagonist name) and do NOT access saved stories or other personal data.
          </div>
        </div>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">4.2 Payment management</h3>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              <strong>RevenueCat</strong>: securely manages subscriptions
            </li>
            <li>
              <strong>App Store / Google Play</strong>: process payments according to their policies
            </li>
          </ul>
        </div>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">4.3 We NEVER share</h3>
          <ul className="list-disc space-y-2 pl-6">
            <li>We do not sell data to third parties</li>
            <li>We do not use data for advertising</li>
            <li>We do not build marketing profiles</li>
          </ul>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">5. SECURITY AND RETENTION</h2>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">5.1 Local storage</h3>
          <div className="rounded-xl border-l-4 border-sky-500 bg-sky-50 px-5 py-4">
            <ul className="list-disc space-y-2 pl-6">
              <li>
                <strong>All data is stored locally</strong> on the device
              </li>
              <li>
                <strong>Encryption</strong>: sensitive data is encrypted
              </li>
              <li>
                <strong>No cloud sync</strong>: data is not uploaded to external servers
              </li>
            </ul>
          </div>
        </div>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">5.2 Retention</h3>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              <strong>App data</strong>: kept until the app is uninstalled
            </li>
            <li>
              <strong>Backups</strong>: local only, managed by the user
            </li>
            <li>
              <strong>Deletion</strong>: available at any time through app settings
            </li>
          </ul>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">6. USER RIGHTS (GDPR)</h2>
        <p>You have the right to:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            <strong>Access</strong>: know which data we hold
          </li>
          <li>
            <strong>Rectification</strong>: correct inaccurate data
          </li>
          <li>
            <strong>Erasure</strong>: delete all data
          </li>
          <li>
            <strong>Portability</strong>: export your stories
          </li>
          <li>
            <strong>Objection</strong>: object to processing
          </li>
          <li>
            <strong>Restriction</strong>: limit how data is used
          </li>
        </ul>
        <div className="rounded-xl border-l-4 border-amber-500 bg-amber-50 px-5 py-4">
          <strong>How to exercise these rights:</strong> Contact us at marinopanariello@gmail.com or use the in-app settings.
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">7. CHILDREN AND CONSENT</h2>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">7.1 Safeguarding minors</h3>
          <ul className="list-disc space-y-2 pl-6">
            <li>App designed specifically for children aged 0-12</li>
            <li>Content is always appropriate and safe</li>
            <li>No sensitive data is collected</li>
            <li>Built-in parental control</li>
          </ul>
        </div>

        <div className="space-y-3">
          <h3 className="text-xl font-semibold text-slate-700">7.2 Parental consent</h3>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              <strong>Under 13</strong>: parental consent is required
            </li>
            <li>
              <strong>Installing the app</strong>: implies consent for basic features
            </li>
            <li>
              <strong>Optional data</strong>: explicit consent required
            </li>
          </ul>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">8. INTERNATIONAL TRANSFERS</h2>
        <p>The AI services used may involve transfers to:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            <strong>United States</strong> (Google, Amazon)
          </li>
          <li>
            <strong>Europe</strong> (selected Runware servers)
          </li>
        </ul>
        <p>All providers apply safeguards compliant with the GDPR.</p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">9. CHANGES TO THIS POLICY</h2>
        <p>We will notify of significant changes via:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>In-app notification</li>
          <li>Email (if provided)</li>
          <li>Updates on this page</li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">10. CONTACT AND COMPLAINTS</h2>
        <div className="rounded-xl border border-slate-200 bg-slate-50 px-5 py-4">
          <p className="font-semibold">For privacy questions:</p>
          <p>Email: <a className="text-blue-600 underline-offset-4 hover:underline" href="mailto:marinopanariello@gmail.com">marinopanariello@gmail.com</a></p>
          <p>Response time: within 30 days</p>
          <p className="mt-4 font-semibold">To raise a complaint:</p>
          <p>You can contact the Data Protection Authority in your country.</p>
          <p className="mt-4 font-semibold">Supervisory authority in Italy:</p>
          <p>Garante per la protezione dei dati personali<br />Email: garante@gpdp.it</p>
        </div>
      </section>

      <footer className="border-t border-slate-200 pt-6 text-sm text-slate-500">
        <p>© 2024 Fiabe Magiche. All rights reserved.</p>
        <p>This notice complies with the EU General Data Protection Regulation (GDPR) 2016/679.</p>
      </footer>
    </LegalLayout>
  )
}
