import { LegalLayout } from '../../../components/LegalLayout'

export const metadata = {
  title: 'Privacy Policy – All Party Animation',
  description: 'Privacy notice describing how personal data is processed within the All Party Animation management platform.',
}

export default function Page() {
  return (
    <LegalLayout>
      <header className="space-y-2 border-b border-slate-200 pb-6">
        <h1 className="text-3xl font-semibold tracking-tight">Privacy Notice</h1>
        <p className="text-slate-600">Last updated: 16 September 2025</p>
      </header>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">1. Data Controller</h2>
        <p>
          The data controller is <strong>Marino Panariello</strong>, Alcide De Gasperi 49, 80059 Torre del Greco (NA), Italy. Contacts:{' '}
          <a className="text-blue-600 underline-offset-4 hover:underline" href="mailto:marinopanariello@gmail.com">marinopanariello@gmail.com</a>, Certified Email{' '}
          <a className="text-blue-600 underline-offset-4 hover:underline" href="mailto:marinopanariello@pec.it">marinopanariello@pec.it</a>.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">2. Data Collected</h2>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            <strong>Identity and contact data</strong>: first name, last name, email, and optional phone number provided during onboarding.
          </li>
          <li>
            <strong>Login credentials</strong>: email and password managed via Supabase with hashing measures.
          </li>
          <li>
            <strong>Operational data</strong>: details about events, materials, and internal activities recorded by users.
          </li>
          <li>
            <strong>Technical data</strong>: IP address, device identifiers, and access logs generated by the hosting provider (Vercel) and database (Supabase).
          </li>
          <li>
            <strong>Push tokens</strong>: identifiers generated through Firebase/Capacitor for notifications, linked to the Supabase account.
          </li>
          <li>
            <strong>Cookies and similar technologies</strong>: functional cookies such as “sidebar:state”, data saved in localStorage to manage redirects from push notifications, plus technical cookies from hosting and analytics providers.
          </li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">3. Purposes and Legal Bases</h2>
        <div className="overflow-x-auto">
          <table className="w-full border-collapse overflow-hidden rounded-xl text-left text-sm shadow-sm">
            <thead className="bg-slate-100 text-slate-700">
              <tr>
                <th className="border border-slate-200 px-4 py-3 font-semibold">Purpose</th>
                <th className="border border-slate-200 px-4 py-3 font-semibold">Legal basis</th>
              </tr>
            </thead>
            <tbody>
              <tr className="odd:bg-white even:bg-slate-50">
                <td className="border border-slate-200 px-4 py-3">Account management, authentication, and internal authorisations.</td>
                <td className="border border-slate-200 px-4 py-3">Performance of pre-contractual/contractual measures (Art. 6(1)(b) GDPR).</td>
              </tr>
              <tr className="odd:bg-white even:bg-slate-50">
                <td className="border border-slate-200 px-4 py-3">Operational communications and delivery of push notifications.</td>
                <td className="border border-slate-200 px-4 py-3">Legitimate interest in coordinating the agency (Art. 6(1)(f) GDPR).</td>
              </tr>
              <tr className="odd:bg-white even:bg-slate-50">
                <td className="border border-slate-200 px-4 py-3">Usage analytics and service improvement.</td>
                <td className="border border-slate-200 px-4 py-3">Legitimate interest; data is aggregated/anonymised (Art. 6(1)(f) GDPR).</td>
              </tr>
              <tr className="odd:bg-white even:bg-slate-50">
                <td className="border border-slate-200 px-4 py-3">Compliance with legal obligations and responses to authority requests.</td>
                <td className="border border-slate-200 px-4 py-3">Legal obligation (Art. 6(1)(c) GDPR).</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">4. Data Retention</h2>
        <p>
          Data is kept for as long as needed to deliver the platform and meet fiscal/accounting duties. Inactive accounts may be deactivated or anonymised after 24 months with no access, unless otherwise requested by the organisation.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">5. Sharing and Transfers</h2>
        <p>
          Data is primarily processed within the EU/EEA. Providers such as Vercel and Supabase may transfer information outside the EU (e.g., the United States) under appropriate contractual safeguards (Standard Contractual Clauses) and technical protections. No profiling or data sales to third parties occur.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">6. Security</h2>
        <p>
          Technical and organisational measures protect the data: Supabase authentication, encrypted connections (HTTPS), centralised access management, and operation logging. Users must keep credentials confidential and update passwords regularly.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">7. Data Subject Rights</h2>
        <ul className="list-disc space-y-2 pl-6">
          <li>Access, rectification, erasure, and restriction of processing.</li>
          <li>Objection to processing based on legitimate interest.</li>
          <li>Portability of the data provided.</li>
          <li>Withdrawal of consent (where given) without affecting prior processing.</li>
          <li>Complaint to the Italian Data Protection Authority (www.garanteprivacy.it).</li>
        </ul>
        <p>
          To exercise these rights, send a request to{' '}
          <a className="text-blue-600 underline-offset-4 hover:underline" href="mailto:marinopanariello@gmail.com">marinopanariello@gmail.com</a> or the certified email listed above.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">8. Third-Party Services</h2>
        <ul className="list-disc space-y-2 pl-6">
          <li>
            <strong>Supabase</strong> (database and authentication) –{' '}
            <a className="text-blue-600 underline-offset-4 hover:underline" href="https://supabase.com/docs/guides/platform/privacy">Privacy Policy</a>.
          </li>
          <li>
            <strong>Vercel</strong> (hosting and analytics) –{' '}
            <a className="text-blue-600 underline-offset-4 hover:underline" href="https://vercel.com/legal/privacy-policy">Privacy Policy</a>.
          </li>
          <li>
            <strong>Firebase Cloud Messaging</strong> (push notifications) –{' '}
            <a className="text-blue-600 underline-offset-4 hover:underline" href="https://firebase.google.com/support/privacy">Privacy Policy</a>.
          </li>
        </ul>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold tracking-tight text-slate-800">9. Changes to this Notice</h2>
        <p>
          The controller may update this notice to reflect regulatory or organisational changes. Updated versions are published on the official website. Continued use of the platform implies acceptance of the changes.
        </p>
      </section>

      <footer className="border-t border-slate-200 pt-6 text-sm text-slate-500">
        <p>
          For any privacy questions, contact{' '}
          <a className="text-blue-600 underline-offset-4 hover:underline" href="mailto:marinopanariello@gmail.com">marinopanariello@gmail.com</a>.
        </p>
      </footer>
    </LegalLayout>
  )
}
